export type EmojiItem = {
  emoji: string;
  name: string;
  keywords: string[];
};

export type EmojiCategory = {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
};

const FREQUENT_KEY = 'ecto:frequent-emojis';
const MAX_FREQUENT = 32;

// --- Categories ---

const smileys: EmojiItem[] = [
  { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile'] },
  { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile'] },
  { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy'] },
  { emoji: '😁', name: 'beaming face', keywords: ['grin', 'happy'] },
  { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh'] },
  { emoji: '😅', name: 'grinning face with sweat', keywords: ['awkward', 'nervous'] },
  { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'lol'] },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'lol'] },
  { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
  { emoji: '🙃', name: 'upside-down face', keywords: ['sarcasm'] },
  { emoji: '😉', name: 'winking face', keywords: ['wink'] },
  { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy'] },
  { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
  { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore'] },
  { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush'] },
  { emoji: '🤩', name: 'star-struck', keywords: ['excited', 'wow'] },
  { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'] },
  { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'] },
  { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'] },
  { emoji: '🥲', name: 'smiling face with tear', keywords: ['sad', 'happy'] },
  { emoji: '😋', name: 'face savoring food', keywords: ['yum', 'delicious'] },
  { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'playful'] },
  { emoji: '😜', name: 'winking face with tongue', keywords: ['tongue', 'wink'] },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild'] },
  { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue'] },
  { emoji: '🤑', name: 'money-mouth face', keywords: ['money', 'rich'] },
  { emoji: '🤗', name: 'smiling face with open hands', keywords: ['hug'] },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'] },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm'] },
  { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect'] },
  { emoji: '🤐', name: 'zipper-mouth face', keywords: ['silent', 'mute'] },
  { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'skeptical'] },
  { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank'] },
  { emoji: '😑', name: 'expressionless face', keywords: ['blank'] },
  { emoji: '😶', name: 'face without mouth', keywords: ['silent'] },
  { emoji: '🫥', name: 'dotted line face', keywords: ['invisible', 'hidden'] },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'suggestive'] },
  { emoji: '😒', name: 'unamused face', keywords: ['annoyed', 'meh'] },
  { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll'] },
  { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'cringe'] },
  { emoji: '🤥', name: 'lying face', keywords: ['pinocchio', 'lie'] },
  { emoji: '🫨', name: 'shaking face', keywords: ['shock', 'vibrate'] },
  { emoji: '😌', name: 'relieved face', keywords: ['relief', 'calm'] },
  { emoji: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'] },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired'] },
  { emoji: '🤤', name: 'drooling face', keywords: ['drool'] },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'] },
  { emoji: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
  { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'] },
  { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'] },
  { emoji: '🤮', name: 'face vomiting', keywords: ['puke', 'sick'] },
  { emoji: '🥵', name: 'hot face', keywords: ['hot', 'sweating'] },
  { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing'] },
  { emoji: '🥴', name: 'woozy face', keywords: ['drunk', 'dizzy'] },
  { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead'] },
  { emoji: '😵‍💫', name: 'face with spiral eyes', keywords: ['dizzy', 'hypnotized'] },
  { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shock'] },
  { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'yeehaw'] },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'] },
  { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'] },
  { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
  { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek'] },
  { emoji: '🧐', name: 'face with monocle', keywords: ['classy', 'inspect'] },
  { emoji: '😕', name: 'confused face', keywords: ['confused'] },
  { emoji: '🫤', name: 'face with diagonal mouth', keywords: ['unsure', 'meh'] },
  { emoji: '😟', name: 'worried face', keywords: ['worried', 'concerned'] },
  { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad'] },
  { emoji: '☹️', name: 'frowning face', keywords: ['sad'] },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow'] },
  { emoji: '😯', name: 'hushed face', keywords: ['surprised'] },
  { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'surprised'] },
  { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
  { emoji: '🥺', name: 'pleading face', keywords: ['puppy eyes', 'please'] },
  { emoji: '🥹', name: 'face holding back tears', keywords: ['proud', 'touched'] },
  { emoji: '😦', name: 'frowning face with open mouth', keywords: ['surprised', 'sad'] },
  { emoji: '😧', name: 'anguished face', keywords: ['pain'] },
  { emoji: '😨', name: 'fearful face', keywords: ['scared', 'afraid'] },
  { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious'] },
  { emoji: '😥', name: 'sad but relieved face', keywords: ['sad'] },
  { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad'] },
  { emoji: '😭', name: 'loudly crying face', keywords: ['sob', 'cry'] },
  { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'horror'] },
  { emoji: '😖', name: 'confounded face', keywords: ['frustrated'] },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle'] },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad'] },
  { emoji: '😓', name: 'downcast face with sweat', keywords: ['hard work'] },
  { emoji: '😩', name: 'weary face', keywords: ['tired'] },
  { emoji: '😫', name: 'tired face', keywords: ['exhausted'] },
  { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'bored'] },
  { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'triumph'] },
  { emoji: '😡', name: 'enraged face', keywords: ['angry', 'mad'] },
  { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
  { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['swear', 'curse'] },
  { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil'] },
  { emoji: '👿', name: 'angry face with horns', keywords: ['devil'] },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'death'] },
  { emoji: '☠️', name: 'skull and crossbones', keywords: ['death', 'danger'] },
  { emoji: '💩', name: 'pile of poo', keywords: ['poop'] },
  { emoji: '🤡', name: 'clown face', keywords: ['clown'] },
  { emoji: '👹', name: 'ogre', keywords: ['monster'] },
  { emoji: '👺', name: 'goblin', keywords: ['monster'] },
  { emoji: '👻', name: 'ghost', keywords: ['halloween'] },
  { emoji: '👽', name: 'alien', keywords: ['ufo'] },
  { emoji: '👾', name: 'alien monster', keywords: ['game', 'space'] },
  { emoji: '🤖', name: 'robot', keywords: ['bot'] },
  { emoji: '😺', name: 'grinning cat', keywords: ['cat', 'happy'] },
  { emoji: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat'] },
  { emoji: '😹', name: 'cat with tears of joy', keywords: ['cat', 'laugh'] },
  { emoji: '😻', name: 'smiling cat with heart-eyes', keywords: ['cat', 'love'] },
  { emoji: '😼', name: 'cat with wry smile', keywords: ['cat', 'smirk'] },
  { emoji: '😽', name: 'kissing cat', keywords: ['cat', 'kiss'] },
  { emoji: '🙀', name: 'weary cat', keywords: ['cat', 'surprised'] },
  { emoji: '😿', name: 'crying cat', keywords: ['cat', 'sad'] },
  { emoji: '😾', name: 'pouting cat', keywords: ['cat', 'angry'] },
  { emoji: '🫶', name: 'heart hands', keywords: ['love', 'gesture'] },
  { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye'] },
  { emoji: '🤚', name: 'raised back of hand', keywords: ['hand'] },
  { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['hand'] },
  { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five'] },
  { emoji: '🖖', name: 'vulcan salute', keywords: ['spock'] },
  { emoji: '🫱', name: 'rightwards hand', keywords: ['hand'] },
  { emoji: '🫲', name: 'leftwards hand', keywords: ['hand'] },
  { emoji: '🫳', name: 'palm down hand', keywords: ['hand'] },
  { emoji: '🫴', name: 'palm up hand', keywords: ['hand'] },
  { emoji: '👌', name: 'OK hand', keywords: ['ok', 'perfect'] },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian'] },
  { emoji: '🤏', name: 'pinching hand', keywords: ['small', 'tiny'] },
  { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'v'] },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
  { emoji: '🫰', name: 'hand with index finger and thumb crossed', keywords: ['money', 'snap'] },
  { emoji: '🤟', name: 'love-you gesture', keywords: ['love'] },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock'] },
  { emoji: '🤙', name: 'call me hand', keywords: ['call', 'shaka'] },
  { emoji: '👈', name: 'backhand index pointing left', keywords: ['left'] },
  { emoji: '👉', name: 'backhand index pointing right', keywords: ['right'] },
  { emoji: '👆', name: 'backhand index pointing up', keywords: ['up'] },
  { emoji: '🖕', name: 'middle finger', keywords: ['rude'] },
  { emoji: '👇', name: 'backhand index pointing down', keywords: ['down'] },
  { emoji: '☝️', name: 'index pointing up', keywords: ['point'] },
  { emoji: '🫵', name: 'index pointing at the viewer', keywords: ['you'] },
  { emoji: '👍', name: 'thumbs up', keywords: ['like', 'approve', 'yes'] },
  { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'disapprove', 'no'] },
  { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
  { emoji: '👊', name: 'oncoming fist', keywords: ['punch'] },
  { emoji: '🤛', name: 'left-facing fist', keywords: ['fist bump'] },
  { emoji: '🤜', name: 'right-facing fist', keywords: ['fist bump'] },
  { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause'] },
  { emoji: '🙌', name: 'raising hands', keywords: ['celebrate'] },
  { emoji: '🫶', name: 'heart hands', keywords: ['love'] },
  { emoji: '👐', name: 'open hands', keywords: ['hands'] },
  { emoji: '🤲', name: 'palms up together', keywords: ['pray'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree'] },
  { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks'] },
  { emoji: '✍️', name: 'writing hand', keywords: ['write'] },
  { emoji: '💅', name: 'nail polish', keywords: ['nails', 'beauty'] },
  { emoji: '🤳', name: 'selfie', keywords: ['selfie', 'phone'] },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'see'] },
  { emoji: '👁️', name: 'eye', keywords: ['look'] },
  { emoji: '👅', name: 'tongue', keywords: ['tongue'] },
  { emoji: '👄', name: 'mouth', keywords: ['lips'] },
  { emoji: '🧠', name: 'brain', keywords: ['smart', 'think'] },
  { emoji: '❤️', name: 'red heart', keywords: ['love'] },
  { emoji: '🧡', name: 'orange heart', keywords: ['love'] },
  { emoji: '💛', name: 'yellow heart', keywords: ['love'] },
  { emoji: '💚', name: 'green heart', keywords: ['love'] },
  { emoji: '💙', name: 'blue heart', keywords: ['love'] },
  { emoji: '💜', name: 'purple heart', keywords: ['love'] },
  { emoji: '🖤', name: 'black heart', keywords: ['love'] },
  { emoji: '🤍', name: 'white heart', keywords: ['love'] },
  { emoji: '🤎', name: 'brown heart', keywords: ['love'] },
  { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
  { emoji: '❤️‍🔥', name: 'heart on fire', keywords: ['love', 'passion'] },
  { emoji: '❤️‍🩹', name: 'mending heart', keywords: ['healing'] },
  { emoji: '💕', name: 'two hearts', keywords: ['love'] },
  { emoji: '💞', name: 'revolving hearts', keywords: ['love'] },
  { emoji: '💓', name: 'beating heart', keywords: ['love'] },
  { emoji: '💗', name: 'growing heart', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love'] },
  { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'] },
  { emoji: '💝', name: 'heart with ribbon', keywords: ['love', 'gift'] },
  { emoji: '💟', name: 'heart decoration', keywords: ['love'] },
  { emoji: '💯', name: 'hundred points', keywords: ['perfect', '100'] },
  { emoji: '💢', name: 'anger symbol', keywords: ['angry'] },
  { emoji: '💥', name: 'collision', keywords: ['boom', 'explosion'] },
  { emoji: '💫', name: 'dizzy', keywords: ['star'] },
  { emoji: '💦', name: 'sweat droplets', keywords: ['sweat'] },
  { emoji: '💨', name: 'dashing away', keywords: ['wind', 'fast'] },
  { emoji: '🕳️', name: 'hole', keywords: ['hole'] },
  { emoji: '💣', name: 'bomb', keywords: ['bomb'] },
  { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message'] },
  { emoji: '💤', name: 'zzz', keywords: ['sleep'] },
];

const animals: EmojiItem[] = [
  { emoji: '🐶', name: 'dog face', keywords: ['puppy', 'pet'] },
  { emoji: '🐱', name: 'cat face', keywords: ['kitty', 'pet'] },
  { emoji: '🐭', name: 'mouse face', keywords: ['mouse'] },
  { emoji: '🐹', name: 'hamster', keywords: ['pet'] },
  { emoji: '🐰', name: 'rabbit face', keywords: ['bunny'] },
  { emoji: '🦊', name: 'fox', keywords: ['fox'] },
  { emoji: '🐻', name: 'bear', keywords: ['bear'] },
  { emoji: '🐼', name: 'panda', keywords: ['panda'] },
  { emoji: '🐻‍❄️', name: 'polar bear', keywords: ['bear', 'arctic'] },
  { emoji: '🐨', name: 'koala', keywords: ['koala'] },
  { emoji: '🐯', name: 'tiger face', keywords: ['tiger'] },
  { emoji: '🦁', name: 'lion', keywords: ['lion', 'king'] },
  { emoji: '🐮', name: 'cow face', keywords: ['cow'] },
  { emoji: '🐷', name: 'pig face', keywords: ['pig'] },
  { emoji: '🐸', name: 'frog', keywords: ['frog', 'toad'] },
  { emoji: '🐵', name: 'monkey face', keywords: ['monkey'] },
  { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'shy'] },
  { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey'] },
  { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey'] },
  { emoji: '🐒', name: 'monkey', keywords: ['monkey'] },
  { emoji: '🐔', name: 'chicken', keywords: ['chicken'] },
  { emoji: '🐧', name: 'penguin', keywords: ['penguin'] },
  { emoji: '🐦', name: 'bird', keywords: ['bird'] },
  { emoji: '🐤', name: 'baby chick', keywords: ['chick'] },
  { emoji: '🐣', name: 'hatching chick', keywords: ['chick', 'egg'] },
  { emoji: '🐥', name: 'front-facing baby chick', keywords: ['chick'] },
  { emoji: '🦆', name: 'duck', keywords: ['duck'] },
  { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
  { emoji: '🦉', name: 'owl', keywords: ['owl', 'wise'] },
  { emoji: '🦇', name: 'bat', keywords: ['bat', 'vampire'] },
  { emoji: '🐺', name: 'wolf', keywords: ['wolf'] },
  { emoji: '🐗', name: 'boar', keywords: ['pig'] },
  { emoji: '🐴', name: 'horse face', keywords: ['horse'] },
  { emoji: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
  { emoji: '🐝', name: 'honeybee', keywords: ['bee'] },
  { emoji: '🪱', name: 'worm', keywords: ['worm'] },
  { emoji: '🐛', name: 'bug', keywords: ['insect'] },
  { emoji: '🦋', name: 'butterfly', keywords: ['butterfly'] },
  { emoji: '🐌', name: 'snail', keywords: ['slow'] },
  { emoji: '🐞', name: 'lady beetle', keywords: ['ladybug'] },
  { emoji: '🐜', name: 'ant', keywords: ['ant'] },
  { emoji: '🪰', name: 'fly', keywords: ['insect'] },
  { emoji: '🪲', name: 'beetle', keywords: ['bug'] },
  { emoji: '🦗', name: 'cricket', keywords: ['cricket'] },
  { emoji: '🕷️', name: 'spider', keywords: ['spider'] },
  { emoji: '🦂', name: 'scorpion', keywords: ['scorpion'] },
  { emoji: '🐢', name: 'turtle', keywords: ['turtle', 'slow'] },
  { emoji: '🐍', name: 'snake', keywords: ['snake'] },
  { emoji: '🦎', name: 'lizard', keywords: ['reptile'] },
  { emoji: '🦖', name: 'T-Rex', keywords: ['dinosaur'] },
  { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur'] },
  { emoji: '🐙', name: 'octopus', keywords: ['octopus'] },
  { emoji: '🦑', name: 'squid', keywords: ['squid'] },
  { emoji: '🦐', name: 'shrimp', keywords: ['shrimp'] },
  { emoji: '🦞', name: 'lobster', keywords: ['lobster'] },
  { emoji: '🦀', name: 'crab', keywords: ['crab'] },
  { emoji: '🐡', name: 'blowfish', keywords: ['fish'] },
  { emoji: '🐠', name: 'tropical fish', keywords: ['fish'] },
  { emoji: '🐟', name: 'fish', keywords: ['fish'] },
  { emoji: '🐬', name: 'dolphin', keywords: ['dolphin'] },
  { emoji: '🐳', name: 'spouting whale', keywords: ['whale'] },
  { emoji: '🐋', name: 'whale', keywords: ['whale'] },
  { emoji: '🦈', name: 'shark', keywords: ['shark'] },
  { emoji: '🐊', name: 'crocodile', keywords: ['croc', 'alligator'] },
  { emoji: '🐅', name: 'tiger', keywords: ['tiger'] },
  { emoji: '🐆', name: 'leopard', keywords: ['leopard'] },
  { emoji: '🦓', name: 'zebra', keywords: ['zebra'] },
  { emoji: '🦍', name: 'gorilla', keywords: ['ape'] },
  { emoji: '🦧', name: 'orangutan', keywords: ['ape'] },
  { emoji: '🐘', name: 'elephant', keywords: ['elephant'] },
  { emoji: '🦛', name: 'hippopotamus', keywords: ['hippo'] },
  { emoji: '🦏', name: 'rhinoceros', keywords: ['rhino'] },
  { emoji: '🐪', name: 'camel', keywords: ['camel', 'desert'] },
  { emoji: '🐫', name: 'two-hump camel', keywords: ['camel'] },
  { emoji: '🦒', name: 'giraffe', keywords: ['giraffe'] },
  { emoji: '🦘', name: 'kangaroo', keywords: ['kangaroo'] },
  { emoji: '🦬', name: 'bison', keywords: ['buffalo'] },
  { emoji: '🐃', name: 'water buffalo', keywords: ['buffalo'] },
  { emoji: '🐂', name: 'ox', keywords: ['ox'] },
  { emoji: '🐄', name: 'cow', keywords: ['cow'] },
  { emoji: '🐎', name: 'horse', keywords: ['horse', 'racing'] },
  { emoji: '🐖', name: 'pig', keywords: ['pig'] },
  { emoji: '🐏', name: 'ram', keywords: ['sheep'] },
  { emoji: '🐑', name: 'ewe', keywords: ['sheep'] },
  { emoji: '🦙', name: 'llama', keywords: ['llama', 'alpaca'] },
  { emoji: '🐐', name: 'goat', keywords: ['goat'] },
  { emoji: '🦌', name: 'deer', keywords: ['deer'] },
  { emoji: '🐕', name: 'dog', keywords: ['dog'] },
  { emoji: '🐩', name: 'poodle', keywords: ['dog'] },
  { emoji: '🦮', name: 'guide dog', keywords: ['dog'] },
  { emoji: '🐈', name: 'cat', keywords: ['cat'] },
  { emoji: '🐈‍⬛', name: 'black cat', keywords: ['cat'] },
  { emoji: '🐓', name: 'rooster', keywords: ['chicken'] },
  { emoji: '🦃', name: 'turkey', keywords: ['thanksgiving'] },
  { emoji: '🦤', name: 'dodo', keywords: ['extinct'] },
  { emoji: '🦚', name: 'peacock', keywords: ['bird'] },
  { emoji: '🦜', name: 'parrot', keywords: ['bird'] },
  { emoji: '🦢', name: 'swan', keywords: ['bird'] },
  { emoji: '🦩', name: 'flamingo', keywords: ['bird', 'pink'] },
  { emoji: '🕊️', name: 'dove', keywords: ['peace', 'bird'] },
  { emoji: '🐇', name: 'rabbit', keywords: ['bunny'] },
  { emoji: '🦝', name: 'raccoon', keywords: ['raccoon'] },
  { emoji: '🦨', name: 'skunk', keywords: ['skunk'] },
  { emoji: '🦡', name: 'badger', keywords: ['badger'] },
  { emoji: '🦫', name: 'beaver', keywords: ['beaver'] },
  { emoji: '🦦', name: 'otter', keywords: ['otter'] },
  { emoji: '🦥', name: 'sloth', keywords: ['lazy', 'slow'] },
  { emoji: '🐁', name: 'mouse', keywords: ['mouse'] },
  { emoji: '🐀', name: 'rat', keywords: ['rat'] },
  { emoji: '🐿️', name: 'chipmunk', keywords: ['squirrel'] },
  { emoji: '🦔', name: 'hedgehog', keywords: ['hedgehog'] },
  { emoji: '🐾', name: 'paw prints', keywords: ['paw', 'pet'] },
  { emoji: '🐉', name: 'dragon', keywords: ['dragon'] },
  { emoji: '🐲', name: 'dragon face', keywords: ['dragon'] },
  { emoji: '🌵', name: 'cactus', keywords: ['cactus', 'desert'] },
  { emoji: '🎄', name: 'Christmas tree', keywords: ['christmas'] },
  { emoji: '🌲', name: 'evergreen tree', keywords: ['tree'] },
  { emoji: '🌳', name: 'deciduous tree', keywords: ['tree'] },
  { emoji: '🌴', name: 'palm tree', keywords: ['tropical'] },
  { emoji: '🪴', name: 'potted plant', keywords: ['plant'] },
  { emoji: '🌱', name: 'seedling', keywords: ['plant', 'grow'] },
  { emoji: '🌿', name: 'herb', keywords: ['plant'] },
  { emoji: '☘️', name: 'shamrock', keywords: ['clover', 'irish'] },
  { emoji: '🍀', name: 'four leaf clover', keywords: ['lucky'] },
  { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring'] },
  { emoji: '🌺', name: 'hibiscus', keywords: ['flower'] },
  { emoji: '🌻', name: 'sunflower', keywords: ['flower'] },
  { emoji: '🌷', name: 'tulip', keywords: ['flower'] },
  { emoji: '🌹', name: 'rose', keywords: ['flower', 'love'] },
  { emoji: '🥀', name: 'wilted flower', keywords: ['dead', 'sad'] },
  { emoji: '🪻', name: 'hyacinth', keywords: ['flower'] },
  { emoji: '🌼', name: 'blossom', keywords: ['flower'] },
  { emoji: '🍂', name: 'fallen leaf', keywords: ['autumn', 'fall'] },
  { emoji: '🍁', name: 'maple leaf', keywords: ['canada', 'fall'] },
  { emoji: '🍃', name: 'leaf fluttering in wind', keywords: ['leaf'] },
  { emoji: '🌾', name: 'sheaf of rice', keywords: ['rice'] },
  { emoji: '🪹', name: 'empty nest', keywords: ['nest'] },
  { emoji: '🪺', name: 'nest with eggs', keywords: ['nest', 'bird'] },
  { emoji: '🍄', name: 'mushroom', keywords: ['mushroom'] },
];

const food: EmojiItem[] = [
  { emoji: '🍇', name: 'grapes', keywords: ['fruit'] },
  { emoji: '🍈', name: 'melon', keywords: ['fruit'] },
  { emoji: '🍉', name: 'watermelon', keywords: ['fruit', 'summer'] },
  { emoji: '🍊', name: 'tangerine', keywords: ['fruit', 'orange'] },
  { emoji: '🍋', name: 'lemon', keywords: ['fruit', 'sour'] },
  { emoji: '🍌', name: 'banana', keywords: ['fruit'] },
  { emoji: '🍍', name: 'pineapple', keywords: ['fruit'] },
  { emoji: '🥭', name: 'mango', keywords: ['fruit'] },
  { emoji: '🍎', name: 'red apple', keywords: ['fruit'] },
  { emoji: '🍏', name: 'green apple', keywords: ['fruit'] },
  { emoji: '🍐', name: 'pear', keywords: ['fruit'] },
  { emoji: '🍑', name: 'peach', keywords: ['fruit'] },
  { emoji: '🍒', name: 'cherries', keywords: ['fruit'] },
  { emoji: '🍓', name: 'strawberry', keywords: ['fruit'] },
  { emoji: '🫐', name: 'blueberries', keywords: ['fruit'] },
  { emoji: '🥝', name: 'kiwi fruit', keywords: ['fruit'] },
  { emoji: '🍅', name: 'tomato', keywords: ['vegetable'] },
  { emoji: '🫒', name: 'olive', keywords: ['food'] },
  { emoji: '🥥', name: 'coconut', keywords: ['fruit'] },
  { emoji: '🥑', name: 'avocado', keywords: ['fruit', 'guacamole'] },
  { emoji: '🍆', name: 'eggplant', keywords: ['vegetable'] },
  { emoji: '🥔', name: 'potato', keywords: ['vegetable'] },
  { emoji: '🥕', name: 'carrot', keywords: ['vegetable'] },
  { emoji: '🌽', name: 'ear of corn', keywords: ['corn', 'vegetable'] },
  { emoji: '🌶️', name: 'hot pepper', keywords: ['spicy'] },
  { emoji: '🫑', name: 'bell pepper', keywords: ['vegetable'] },
  { emoji: '🥒', name: 'cucumber', keywords: ['vegetable'] },
  { emoji: '🥬', name: 'leafy green', keywords: ['vegetable', 'salad'] },
  { emoji: '🥦', name: 'broccoli', keywords: ['vegetable'] },
  { emoji: '🧄', name: 'garlic', keywords: ['food'] },
  { emoji: '🧅', name: 'onion', keywords: ['food'] },
  { emoji: '🥜', name: 'peanuts', keywords: ['nut'] },
  { emoji: '🫘', name: 'beans', keywords: ['food'] },
  { emoji: '🌰', name: 'chestnut', keywords: ['nut'] },
  { emoji: '🫚', name: 'ginger', keywords: ['spice'] },
  { emoji: '🍞', name: 'bread', keywords: ['food'] },
  { emoji: '🥐', name: 'croissant', keywords: ['pastry', 'french'] },
  { emoji: '🥖', name: 'baguette bread', keywords: ['french'] },
  { emoji: '🫓', name: 'flatbread', keywords: ['bread'] },
  { emoji: '🥨', name: 'pretzel', keywords: ['snack'] },
  { emoji: '🥯', name: 'bagel', keywords: ['bread'] },
  { emoji: '🥞', name: 'pancakes', keywords: ['breakfast'] },
  { emoji: '🧇', name: 'waffle', keywords: ['breakfast'] },
  { emoji: '🧀', name: 'cheese wedge', keywords: ['cheese'] },
  { emoji: '🍖', name: 'meat on bone', keywords: ['meat'] },
  { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat'] },
  { emoji: '🥩', name: 'cut of meat', keywords: ['steak'] },
  { emoji: '🥓', name: 'bacon', keywords: ['meat', 'breakfast'] },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'] },
  { emoji: '🍟', name: 'french fries', keywords: ['fries', 'fast food'] },
  { emoji: '🍕', name: 'pizza', keywords: ['pizza'] },
  { emoji: '🌭', name: 'hot dog', keywords: ['hotdog'] },
  { emoji: '🥪', name: 'sandwich', keywords: ['food'] },
  { emoji: '🌮', name: 'taco', keywords: ['mexican'] },
  { emoji: '🌯', name: 'burrito', keywords: ['mexican'] },
  { emoji: '🫔', name: 'tamale', keywords: ['mexican'] },
  { emoji: '🥙', name: 'stuffed flatbread', keywords: ['falafel', 'pita'] },
  { emoji: '🧆', name: 'falafel', keywords: ['food'] },
  { emoji: '🥚', name: 'egg', keywords: ['food', 'breakfast'] },
  { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying'] },
  { emoji: '🥘', name: 'shallow pan of food', keywords: ['paella'] },
  { emoji: '🍲', name: 'pot of food', keywords: ['stew', 'soup'] },
  { emoji: '🫕', name: 'fondue', keywords: ['cheese'] },
  { emoji: '🥣', name: 'bowl with spoon', keywords: ['cereal'] },
  { emoji: '🥗', name: 'green salad', keywords: ['salad', 'healthy'] },
  { emoji: '🍿', name: 'popcorn', keywords: ['movie', 'snack'] },
  { emoji: '🧈', name: 'butter', keywords: ['food'] },
  { emoji: '🧂', name: 'salt', keywords: ['seasoning'] },
  { emoji: '🥫', name: 'canned food', keywords: ['food'] },
  { emoji: '🍱', name: 'bento box', keywords: ['japanese'] },
  { emoji: '🍘', name: 'rice cracker', keywords: ['japanese'] },
  { emoji: '🍙', name: 'rice ball', keywords: ['japanese'] },
  { emoji: '🍚', name: 'cooked rice', keywords: ['rice'] },
  { emoji: '🍛', name: 'curry rice', keywords: ['curry'] },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles'] },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta'] },
  { emoji: '🍠', name: 'roasted sweet potato', keywords: ['sweet potato'] },
  { emoji: '🍢', name: 'oden', keywords: ['japanese'] },
  { emoji: '🍣', name: 'sushi', keywords: ['japanese'] },
  { emoji: '🍤', name: 'fried shrimp', keywords: ['tempura'] },
  { emoji: '🍥', name: 'fish cake', keywords: ['japanese'] },
  { emoji: '🥮', name: 'moon cake', keywords: ['chinese'] },
  { emoji: '🍡', name: 'dango', keywords: ['japanese'] },
  { emoji: '🥟', name: 'dumpling', keywords: ['food'] },
  { emoji: '🥠', name: 'fortune cookie', keywords: ['chinese'] },
  { emoji: '🥡', name: 'takeout box', keywords: ['chinese'] },
  { emoji: '🦀', name: 'crab', keywords: ['seafood'] },
  { emoji: '🦞', name: 'lobster', keywords: ['seafood'] },
  { emoji: '🦐', name: 'shrimp', keywords: ['seafood'] },
  { emoji: '🦑', name: 'squid', keywords: ['seafood'] },
  { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert'] },
  { emoji: '🍧', name: 'shaved ice', keywords: ['dessert'] },
  { emoji: '🍨', name: 'ice cream', keywords: ['dessert'] },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'] },
  { emoji: '🍪', name: 'cookie', keywords: ['dessert'] },
  { emoji: '🎂', name: 'birthday cake', keywords: ['birthday', 'cake'] },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
  { emoji: '🧁', name: 'cupcake', keywords: ['dessert'] },
  { emoji: '🥧', name: 'pie', keywords: ['dessert'] },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate'] },
  { emoji: '🍬', name: 'candy', keywords: ['sweet'] },
  { emoji: '🍭', name: 'lollipop', keywords: ['candy'] },
  { emoji: '🍮', name: 'custard', keywords: ['dessert'] },
  { emoji: '🍯', name: 'honey pot', keywords: ['honey'] },
  { emoji: '🍼', name: 'baby bottle', keywords: ['milk'] },
  { emoji: '🥛', name: 'glass of milk', keywords: ['milk'] },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea'] },
  { emoji: '🫖', name: 'teapot', keywords: ['tea'] },
  { emoji: '🍵', name: 'teacup without handle', keywords: ['tea'] },
  { emoji: '🍶', name: 'sake', keywords: ['japanese', 'alcohol'] },
  { emoji: '🍾', name: 'bottle with popping cork', keywords: ['champagne'] },
  { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'alcohol'] },
  { emoji: '🍸', name: 'cocktail glass', keywords: ['martini', 'alcohol'] },
  { emoji: '🍹', name: 'tropical drink', keywords: ['cocktail'] },
  { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'alcohol'] },
  { emoji: '🍻', name: 'clinking beer mugs', keywords: ['cheers'] },
  { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers', 'toast'] },
  { emoji: '🥃', name: 'tumbler glass', keywords: ['whiskey'] },
  { emoji: '🫗', name: 'pouring liquid', keywords: ['pour'] },
  { emoji: '🥤', name: 'cup with straw', keywords: ['soda'] },
  { emoji: '🧋', name: 'bubble tea', keywords: ['boba'] },
  { emoji: '🧃', name: 'beverage box', keywords: ['juice'] },
  { emoji: '🧉', name: 'maté', keywords: ['drink'] },
  { emoji: '🧊', name: 'ice', keywords: ['cold'] },
  { emoji: '🥢', name: 'chopsticks', keywords: ['asian'] },
  { emoji: '🍽️', name: 'fork and knife with plate', keywords: ['dining'] },
  { emoji: '🍴', name: 'fork and knife', keywords: ['dining'] },
  { emoji: '🥄', name: 'spoon', keywords: ['utensil'] },
];

const activities: EmojiItem[] = [
  { emoji: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'] },
  { emoji: '🏀', name: 'basketball', keywords: ['sport'] },
  { emoji: '🏈', name: 'american football', keywords: ['sport'] },
  { emoji: '⚾', name: 'baseball', keywords: ['sport'] },
  { emoji: '🥎', name: 'softball', keywords: ['sport'] },
  { emoji: '🎾', name: 'tennis', keywords: ['sport'] },
  { emoji: '🏐', name: 'volleyball', keywords: ['sport'] },
  { emoji: '🏉', name: 'rugby football', keywords: ['sport'] },
  { emoji: '🥏', name: 'flying disc', keywords: ['frisbee'] },
  { emoji: '🎱', name: 'pool 8 ball', keywords: ['billiards'] },
  { emoji: '🪀', name: 'yo-yo', keywords: ['toy'] },
  { emoji: '🏓', name: 'ping pong', keywords: ['table tennis'] },
  { emoji: '🏸', name: 'badminton', keywords: ['sport'] },
  { emoji: '🏒', name: 'ice hockey', keywords: ['sport'] },
  { emoji: '🏑', name: 'field hockey', keywords: ['sport'] },
  { emoji: '🥍', name: 'lacrosse', keywords: ['sport'] },
  { emoji: '🏏', name: 'cricket game', keywords: ['sport'] },
  { emoji: '🪃', name: 'boomerang', keywords: ['toy'] },
  { emoji: '🥅', name: 'goal net', keywords: ['sport'] },
  { emoji: '⛳', name: 'flag in hole', keywords: ['golf'] },
  { emoji: '🪁', name: 'kite', keywords: ['toy'] },
  { emoji: '🏹', name: 'bow and arrow', keywords: ['archery'] },
  { emoji: '🎣', name: 'fishing pole', keywords: ['fishing'] },
  { emoji: '🤿', name: 'diving mask', keywords: ['diving', 'snorkel'] },
  { emoji: '🥊', name: 'boxing glove', keywords: ['boxing'] },
  { emoji: '🥋', name: 'martial arts uniform', keywords: ['karate'] },
  { emoji: '🎽', name: 'running shirt', keywords: ['sport'] },
  { emoji: '⛸️', name: 'ice skate', keywords: ['skating'] },
  { emoji: '🛷', name: 'sled', keywords: ['winter'] },
  { emoji: '🎿', name: 'skis', keywords: ['skiing'] },
  { emoji: '⛷️', name: 'skier', keywords: ['skiing'] },
  { emoji: '🏂', name: 'snowboarder', keywords: ['snowboard'] },
  { emoji: '🪂', name: 'parachute', keywords: ['skydiving'] },
  { emoji: '🏋️', name: 'person lifting weights', keywords: ['gym', 'fitness'] },
  { emoji: '🤸', name: 'person cartwheeling', keywords: ['gymnastics'] },
  { emoji: '🤼', name: 'people wrestling', keywords: ['wrestling'] },
  { emoji: '🤽', name: 'person playing water polo', keywords: ['sport'] },
  { emoji: '🤾', name: 'person playing handball', keywords: ['sport'] },
  { emoji: '🏌️', name: 'person golfing', keywords: ['golf'] },
  { emoji: '🏇', name: 'horse racing', keywords: ['racing'] },
  { emoji: '🧘', name: 'person in lotus position', keywords: ['yoga', 'meditation'] },
  { emoji: '🏄', name: 'person surfing', keywords: ['surfing'] },
  { emoji: '🏊', name: 'person swimming', keywords: ['swimming'] },
  { emoji: '🚣', name: 'person rowing boat', keywords: ['rowing'] },
  { emoji: '🧗', name: 'person climbing', keywords: ['climbing'] },
  { emoji: '🚴', name: 'person biking', keywords: ['cycling'] },
  { emoji: '🚵', name: 'person mountain biking', keywords: ['cycling'] },
  { emoji: '🎪', name: 'circus tent', keywords: ['circus'] },
  { emoji: '🛹', name: 'skateboard', keywords: ['skating'] },
  { emoji: '🛼', name: 'roller skate', keywords: ['skating'] },
  { emoji: '🎗️', name: 'reminder ribbon', keywords: ['ribbon'] },
  { emoji: '🎟️', name: 'admission tickets', keywords: ['ticket'] },
  { emoji: '🎫', name: 'ticket', keywords: ['admission'] },
  { emoji: '🎖️', name: 'military medal', keywords: ['medal'] },
  { emoji: '🏆', name: 'trophy', keywords: ['winner', 'award'] },
  { emoji: '🏅', name: 'sports medal', keywords: ['medal'] },
  { emoji: '🥇', name: 'gold medal', keywords: ['first', 'winner'] },
  { emoji: '🥈', name: 'silver medal', keywords: ['second'] },
  { emoji: '🥉', name: 'bronze medal', keywords: ['third'] },
  { emoji: '🎮', name: 'video game', keywords: ['gaming', 'controller'] },
  { emoji: '🕹️', name: 'joystick', keywords: ['gaming'] },
  { emoji: '🎲', name: 'game die', keywords: ['dice'] },
  { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle'] },
  { emoji: '♟️', name: 'chess pawn', keywords: ['chess'] },
  { emoji: '🎯', name: 'bullseye', keywords: ['target', 'dart'] },
  { emoji: '🎳', name: 'bowling', keywords: ['bowling'] },
  { emoji: '🎰', name: 'slot machine', keywords: ['gambling'] },
  { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'drama'] },
  { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint'] },
  { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film'] },
  { emoji: '🎤', name: 'microphone', keywords: ['karaoke', 'sing'] },
  { emoji: '🎧', name: 'headphone', keywords: ['music'] },
  { emoji: '🎼', name: 'musical score', keywords: ['music'] },
  { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music'] },
  { emoji: '🥁', name: 'drum', keywords: ['music'] },
  { emoji: '🪘', name: 'long drum', keywords: ['music'] },
  { emoji: '🎷', name: 'saxophone', keywords: ['music', 'jazz'] },
  { emoji: '🎺', name: 'trumpet', keywords: ['music'] },
  { emoji: '🪗', name: 'accordion', keywords: ['music'] },
  { emoji: '🎸', name: 'guitar', keywords: ['music', 'rock'] },
  { emoji: '🎻', name: 'violin', keywords: ['music'] },
  { emoji: '🎵', name: 'musical note', keywords: ['music'] },
  { emoji: '🎶', name: 'musical notes', keywords: ['music'] },
  { emoji: '🎙️', name: 'studio microphone', keywords: ['podcast'] },
  { emoji: '🎚️', name: 'level slider', keywords: ['audio'] },
  { emoji: '🎛️', name: 'control knobs', keywords: ['audio'] },
];

const travel: EmojiItem[] = [
  { emoji: '🚗', name: 'automobile', keywords: ['car'] },
  { emoji: '🚕', name: 'taxi', keywords: ['cab'] },
  { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car'] },
  { emoji: '🚌', name: 'bus', keywords: ['bus'] },
  { emoji: '🚎', name: 'trolleybus', keywords: ['bus'] },
  { emoji: '🏎️', name: 'racing car', keywords: ['race'] },
  { emoji: '🚓', name: 'police car', keywords: ['police'] },
  { emoji: '🚑', name: 'ambulance', keywords: ['medical'] },
  { emoji: '🚒', name: 'fire engine', keywords: ['fire'] },
  { emoji: '🚐', name: 'minibus', keywords: ['van'] },
  { emoji: '🛻', name: 'pickup truck', keywords: ['truck'] },
  { emoji: '🚚', name: 'delivery truck', keywords: ['truck'] },
  { emoji: '🚛', name: 'articulated lorry', keywords: ['truck'] },
  { emoji: '🚜', name: 'tractor', keywords: ['farm'] },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['bike'] },
  { emoji: '🛵', name: 'motor scooter', keywords: ['scooter'] },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike'] },
  { emoji: '🛴', name: 'kick scooter', keywords: ['scooter'] },
  { emoji: '🚏', name: 'bus stop', keywords: ['bus'] },
  { emoji: '🛣️', name: 'motorway', keywords: ['road'] },
  { emoji: '🛤️', name: 'railway track', keywords: ['train'] },
  { emoji: '⛽', name: 'fuel pump', keywords: ['gas'] },
  { emoji: '🚨', name: 'police car light', keywords: ['siren'] },
  { emoji: '🚥', name: 'horizontal traffic light', keywords: ['traffic'] },
  { emoji: '🚦', name: 'vertical traffic light', keywords: ['traffic'] },
  { emoji: '🛑', name: 'stop sign', keywords: ['stop'] },
  { emoji: '🚧', name: 'construction', keywords: ['wip'] },
  { emoji: '⚓', name: 'anchor', keywords: ['ship'] },
  { emoji: '🛟', name: 'ring buoy', keywords: ['lifesaver'] },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat'] },
  { emoji: '🚤', name: 'speedboat', keywords: ['boat'] },
  { emoji: '🛳️', name: 'passenger ship', keywords: ['cruise'] },
  { emoji: '⛴️', name: 'ferry', keywords: ['boat'] },
  { emoji: '🚢', name: 'ship', keywords: ['boat'] },
  { emoji: '✈️', name: 'airplane', keywords: ['plane', 'travel'] },
  { emoji: '🛩️', name: 'small airplane', keywords: ['plane'] },
  { emoji: '🛫', name: 'airplane departure', keywords: ['takeoff'] },
  { emoji: '🛬', name: 'airplane arrival', keywords: ['landing'] },
  { emoji: '🪂', name: 'parachute', keywords: ['skydiving'] },
  { emoji: '💺', name: 'seat', keywords: ['chair'] },
  { emoji: '🚁', name: 'helicopter', keywords: ['helicopter'] },
  { emoji: '🚟', name: 'suspension railway', keywords: ['train'] },
  { emoji: '🚠', name: 'mountain cableway', keywords: ['cable car'] },
  { emoji: '🚡', name: 'aerial tramway', keywords: ['cable car'] },
  { emoji: '🛰️', name: 'satellite', keywords: ['space'] },
  { emoji: '🚀', name: 'rocket', keywords: ['space', 'launch'] },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien'] },
  { emoji: '🌍', name: 'globe showing Europe-Africa', keywords: ['earth', 'world'] },
  { emoji: '🌎', name: 'globe showing Americas', keywords: ['earth', 'world'] },
  { emoji: '🌏', name: 'globe showing Asia-Australia', keywords: ['earth', 'world'] },
  { emoji: '🗺️', name: 'world map', keywords: ['map'] },
  { emoji: '🧭', name: 'compass', keywords: ['navigate'] },
  { emoji: '🏔️', name: 'snow-capped mountain', keywords: ['mountain'] },
  { emoji: '⛰️', name: 'mountain', keywords: ['mountain'] },
  { emoji: '🌋', name: 'volcano', keywords: ['volcano'] },
  { emoji: '🗻', name: 'mount fuji', keywords: ['mountain', 'japan'] },
  { emoji: '🏕️', name: 'camping', keywords: ['tent'] },
  { emoji: '🏖️', name: 'beach with umbrella', keywords: ['beach'] },
  { emoji: '🏜️', name: 'desert', keywords: ['desert'] },
  { emoji: '🏝️', name: 'desert island', keywords: ['island'] },
  { emoji: '🏞️', name: 'national park', keywords: ['nature'] },
  { emoji: '🏟️', name: 'stadium', keywords: ['stadium'] },
  { emoji: '🏛️', name: 'classical building', keywords: ['museum'] },
  { emoji: '🏗️', name: 'building construction', keywords: ['construction'] },
  { emoji: '🧱', name: 'brick', keywords: ['wall'] },
  { emoji: '🏘️', name: 'houses', keywords: ['houses'] },
  { emoji: '🏠', name: 'house', keywords: ['home'] },
  { emoji: '🏡', name: 'house with garden', keywords: ['home'] },
  { emoji: '🏢', name: 'office building', keywords: ['office'] },
  { emoji: '🏣', name: 'Japanese post office', keywords: ['post'] },
  { emoji: '🏥', name: 'hospital', keywords: ['medical'] },
  { emoji: '🏦', name: 'bank', keywords: ['money'] },
  { emoji: '🏨', name: 'hotel', keywords: ['hotel'] },
  { emoji: '🏩', name: 'love hotel', keywords: ['hotel'] },
  { emoji: '🏪', name: 'convenience store', keywords: ['shop'] },
  { emoji: '🏫', name: 'school', keywords: ['education'] },
  { emoji: '🏬', name: 'department store', keywords: ['shop'] },
  { emoji: '🏭', name: 'factory', keywords: ['industry'] },
  { emoji: '🏯', name: 'Japanese castle', keywords: ['castle'] },
  { emoji: '🏰', name: 'castle', keywords: ['castle'] },
  { emoji: '💒', name: 'wedding', keywords: ['chapel'] },
  { emoji: '🗼', name: 'Tokyo tower', keywords: ['tower'] },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['freedom'] },
  { emoji: '⛪', name: 'church', keywords: ['church'] },
  { emoji: '🕌', name: 'mosque', keywords: ['mosque'] },
  { emoji: '🛕', name: 'hindu temple', keywords: ['temple'] },
  { emoji: '🕍', name: 'synagogue', keywords: ['temple'] },
  { emoji: '⛩️', name: 'shinto shrine', keywords: ['shrine', 'japan'] },
  { emoji: '🕋', name: 'kaaba', keywords: ['islam'] },
  { emoji: '⛲', name: 'fountain', keywords: ['water'] },
  { emoji: '⛺', name: 'tent', keywords: ['camping'] },
  { emoji: '🌁', name: 'foggy', keywords: ['fog'] },
  { emoji: '🌃', name: 'night with stars', keywords: ['night'] },
  { emoji: '🏙️', name: 'cityscape', keywords: ['city'] },
  { emoji: '🌄', name: 'sunrise over mountains', keywords: ['sunrise'] },
  { emoji: '🌅', name: 'sunrise', keywords: ['sunrise'] },
  { emoji: '🌆', name: 'cityscape at dusk', keywords: ['sunset'] },
  { emoji: '🌇', name: 'sunset', keywords: ['sunset'] },
  { emoji: '🌉', name: 'bridge at night', keywords: ['bridge'] },
  { emoji: '🌌', name: 'milky way', keywords: ['space', 'stars'] },
  { emoji: '🎠', name: 'carousel horse', keywords: ['amusement'] },
  { emoji: '🎡', name: 'ferris wheel', keywords: ['amusement'] },
  { emoji: '🎢', name: 'roller coaster', keywords: ['amusement'] },
  { emoji: '🚂', name: 'locomotive', keywords: ['train'] },
  { emoji: '🚃', name: 'railway car', keywords: ['train'] },
  { emoji: '🚄', name: 'high-speed train', keywords: ['train'] },
  { emoji: '🚅', name: 'bullet train', keywords: ['train', 'fast'] },
  { emoji: '🚆', name: 'train', keywords: ['train'] },
  { emoji: '🚇', name: 'metro', keywords: ['subway'] },
  { emoji: '🚈', name: 'light rail', keywords: ['train'] },
  { emoji: '🚉', name: 'station', keywords: ['train'] },
  { emoji: '🌈', name: 'rainbow', keywords: ['rainbow'] },
  { emoji: '🌊', name: 'water wave', keywords: ['ocean', 'wave'] },
  { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather'] },
  { emoji: '🌤️', name: 'sun behind small cloud', keywords: ['weather'] },
  { emoji: '⛅', name: 'sun behind cloud', keywords: ['weather'] },
  { emoji: '🌥️', name: 'sun behind large cloud', keywords: ['weather'] },
  { emoji: '☁️', name: 'cloud', keywords: ['weather'] },
  { emoji: '🌦️', name: 'sun behind rain cloud', keywords: ['weather'] },
  { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain'] },
  { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm'] },
  { emoji: '🌩️', name: 'cloud with lightning', keywords: ['thunder'] },
  { emoji: '🌨️', name: 'cloud with snow', keywords: ['snow'] },
  { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'winter'] },
  { emoji: '☃️', name: 'snowman', keywords: ['winter'] },
  { emoji: '⛄', name: 'snowman without snow', keywords: ['winter'] },
  { emoji: '🌬️', name: 'wind face', keywords: ['wind'] },
  { emoji: '💨', name: 'dashing away', keywords: ['wind'] },
  { emoji: '🌪️', name: 'tornado', keywords: ['tornado'] },
  { emoji: '🌫️', name: 'fog', keywords: ['fog'] },
  { emoji: '☔', name: 'umbrella with rain drops', keywords: ['rain'] },
  { emoji: '⭐', name: 'star', keywords: ['star'] },
  { emoji: '🌟', name: 'glowing star', keywords: ['star', 'sparkle'] },
  { emoji: '✨', name: 'sparkles', keywords: ['sparkle', 'magic'] },
  { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night'] },
  { emoji: '🔥', name: 'fire', keywords: ['hot', 'lit'] },
  { emoji: '💧', name: 'droplet', keywords: ['water'] },
];

const objects: EmojiItem[] = [
  { emoji: '⌚', name: 'watch', keywords: ['time'] },
  { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'cell'] },
  { emoji: '📲', name: 'mobile phone with arrow', keywords: ['phone'] },
  { emoji: '💻', name: 'laptop', keywords: ['computer'] },
  { emoji: '⌨️', name: 'keyboard', keywords: ['computer'] },
  { emoji: '🖥️', name: 'desktop computer', keywords: ['computer'] },
  { emoji: '🖨️', name: 'printer', keywords: ['print'] },
  { emoji: '🖱️', name: 'computer mouse', keywords: ['mouse'] },
  { emoji: '🖲️', name: 'trackball', keywords: ['mouse'] },
  { emoji: '🕹️', name: 'joystick', keywords: ['game'] },
  { emoji: '🗜️', name: 'clamp', keywords: ['tool'] },
  { emoji: '💽', name: 'computer disk', keywords: ['minidisc'] },
  { emoji: '💾', name: 'floppy disk', keywords: ['save'] },
  { emoji: '💿', name: 'optical disk', keywords: ['cd'] },
  { emoji: '📀', name: 'dvd', keywords: ['dvd'] },
  { emoji: '📼', name: 'videocassette', keywords: ['vhs'] },
  { emoji: '📷', name: 'camera', keywords: ['photo'] },
  { emoji: '📸', name: 'camera with flash', keywords: ['photo'] },
  { emoji: '📹', name: 'video camera', keywords: ['video'] },
  { emoji: '🎥', name: 'movie camera', keywords: ['film'] },
  { emoji: '📽️', name: 'film projector', keywords: ['movie'] },
  { emoji: '📺', name: 'television', keywords: ['tv'] },
  { emoji: '📻', name: 'radio', keywords: ['radio'] },
  { emoji: '🎙️', name: 'studio microphone', keywords: ['podcast'] },
  { emoji: '📡', name: 'satellite antenna', keywords: ['satellite'] },
  { emoji: '🔋', name: 'battery', keywords: ['power'] },
  { emoji: '🪫', name: 'low battery', keywords: ['power'] },
  { emoji: '🔌', name: 'electric plug', keywords: ['power'] },
  { emoji: '💡', name: 'light bulb', keywords: ['idea'] },
  { emoji: '🔦', name: 'flashlight', keywords: ['light'] },
  { emoji: '🕯️', name: 'candle', keywords: ['light'] },
  { emoji: '🧯', name: 'fire extinguisher', keywords: ['fire'] },
  { emoji: '🛢️', name: 'oil drum', keywords: ['oil'] },
  { emoji: '💰', name: 'money bag', keywords: ['money'] },
  { emoji: '🪙', name: 'coin', keywords: ['money'] },
  { emoji: '💴', name: 'yen banknote', keywords: ['money'] },
  { emoji: '💵', name: 'dollar banknote', keywords: ['money'] },
  { emoji: '💶', name: 'euro banknote', keywords: ['money'] },
  { emoji: '💷', name: 'pound banknote', keywords: ['money'] },
  { emoji: '💸', name: 'money with wings', keywords: ['money', 'expensive'] },
  { emoji: '💳', name: 'credit card', keywords: ['card', 'pay'] },
  { emoji: '🧾', name: 'receipt', keywords: ['bill'] },
  { emoji: '✉️', name: 'envelope', keywords: ['mail', 'email'] },
  { emoji: '📧', name: 'e-mail', keywords: ['email'] },
  { emoji: '📨', name: 'incoming envelope', keywords: ['mail'] },
  { emoji: '📩', name: 'envelope with arrow', keywords: ['mail'] },
  { emoji: '📮', name: 'postbox', keywords: ['mail'] },
  { emoji: '📦', name: 'package', keywords: ['box', 'delivery'] },
  { emoji: '📝', name: 'memo', keywords: ['note', 'write'] },
  { emoji: '📋', name: 'clipboard', keywords: ['paste'] },
  { emoji: '📌', name: 'pushpin', keywords: ['pin'] },
  { emoji: '📍', name: 'round pushpin', keywords: ['location'] },
  { emoji: '📎', name: 'paperclip', keywords: ['attachment'] },
  { emoji: '🖇️', name: 'linked paperclips', keywords: ['attachment'] },
  { emoji: '📏', name: 'straight ruler', keywords: ['ruler'] },
  { emoji: '📐', name: 'triangular ruler', keywords: ['ruler'] },
  { emoji: '✂️', name: 'scissors', keywords: ['cut'] },
  { emoji: '🗃️', name: 'card file box', keywords: ['file'] },
  { emoji: '🗄️', name: 'file cabinet', keywords: ['file'] },
  { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete'] },
  { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure'] },
  { emoji: '🔓', name: 'unlocked', keywords: ['unlock'] },
  { emoji: '🔑', name: 'key', keywords: ['password'] },
  { emoji: '🗝️', name: 'old key', keywords: ['key'] },
  { emoji: '🔨', name: 'hammer', keywords: ['tool'] },
  { emoji: '🪓', name: 'axe', keywords: ['tool'] },
  { emoji: '⛏️', name: 'pick', keywords: ['mining'] },
  { emoji: '⚒️', name: 'hammer and pick', keywords: ['tool'] },
  { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tool'] },
  { emoji: '🔧', name: 'wrench', keywords: ['tool'] },
  { emoji: '🪛', name: 'screwdriver', keywords: ['tool'] },
  { emoji: '🔩', name: 'nut and bolt', keywords: ['tool'] },
  { emoji: '⚙️', name: 'gear', keywords: ['settings'] },
  { emoji: '🧲', name: 'magnet', keywords: ['magnet'] },
  { emoji: '🔫', name: 'water pistol', keywords: ['gun'] },
  { emoji: '💣', name: 'bomb', keywords: ['explosion'] },
  { emoji: '🧨', name: 'firecracker', keywords: ['explosive'] },
  { emoji: '🪚', name: 'carpentry saw', keywords: ['tool'] },
  { emoji: '🔪', name: 'kitchen knife', keywords: ['knife'] },
  { emoji: '🗡️', name: 'dagger', keywords: ['sword'] },
  { emoji: '⚔️', name: 'crossed swords', keywords: ['battle'] },
  { emoji: '🛡️', name: 'shield', keywords: ['defense'] },
  { emoji: '🏳️', name: 'white flag', keywords: ['surrender'] },
  { emoji: '🏴', name: 'black flag', keywords: ['flag'] },
  { emoji: '🚩', name: 'triangular flag', keywords: ['red flag'] },
  { emoji: '📚', name: 'books', keywords: ['library', 'study'] },
  { emoji: '📖', name: 'open book', keywords: ['read'] },
  { emoji: '📕', name: 'closed book', keywords: ['book'] },
  { emoji: '📗', name: 'green book', keywords: ['book'] },
  { emoji: '📘', name: 'blue book', keywords: ['book'] },
  { emoji: '📙', name: 'orange book', keywords: ['book'] },
  { emoji: '📓', name: 'notebook', keywords: ['journal'] },
  { emoji: '📔', name: 'notebook with decorative cover', keywords: ['journal'] },
  { emoji: '📒', name: 'ledger', keywords: ['notebook'] },
  { emoji: '📃', name: 'page with curl', keywords: ['document'] },
  { emoji: '📜', name: 'scroll', keywords: ['document'] },
  { emoji: '📄', name: 'page facing up', keywords: ['document'] },
  { emoji: '📰', name: 'newspaper', keywords: ['news'] },
  { emoji: '🗞️', name: 'rolled-up newspaper', keywords: ['news'] },
  { emoji: '🔖', name: 'bookmark', keywords: ['bookmark'] },
  { emoji: '🏷️', name: 'label', keywords: ['tag'] },
  { emoji: '🪪', name: 'identification card', keywords: ['id'] },
  { emoji: '💊', name: 'pill', keywords: ['medicine'] },
  { emoji: '💉', name: 'syringe', keywords: ['vaccine', 'medical'] },
  { emoji: '🩹', name: 'adhesive bandage', keywords: ['bandaid'] },
  { emoji: '🩺', name: 'stethoscope', keywords: ['medical'] },
  { emoji: '🧪', name: 'test tube', keywords: ['science'] },
  { emoji: '🧫', name: 'petri dish', keywords: ['science'] },
  { emoji: '🧬', name: 'dna', keywords: ['science', 'genetics'] },
  { emoji: '🔬', name: 'microscope', keywords: ['science'] },
  { emoji: '🔭', name: 'telescope', keywords: ['space', 'science'] },
  { emoji: '🩻', name: 'x-ray', keywords: ['medical'] },
  { emoji: '🪞', name: 'mirror', keywords: ['reflection'] },
  { emoji: '🪟', name: 'window', keywords: ['window'] },
  { emoji: '🛏️', name: 'bed', keywords: ['sleep'] },
  { emoji: '🪑', name: 'chair', keywords: ['seat'] },
  { emoji: '🚽', name: 'toilet', keywords: ['bathroom'] },
  { emoji: '🪣', name: 'bucket', keywords: ['bucket'] },
  { emoji: '🧹', name: 'broom', keywords: ['clean'] },
  { emoji: '🧺', name: 'basket', keywords: ['laundry'] },
  { emoji: '🧻', name: 'roll of paper', keywords: ['toilet paper'] },
  { emoji: '🪤', name: 'mouse trap', keywords: ['trap'] },
  { emoji: '🪥', name: 'toothbrush', keywords: ['hygiene'] },
  { emoji: '🧼', name: 'soap', keywords: ['clean'] },
  { emoji: '🫧', name: 'bubbles', keywords: ['clean'] },
  { emoji: '🧽', name: 'sponge', keywords: ['clean'] },
  { emoji: '🧴', name: 'lotion bottle', keywords: ['skincare'] },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'birthday'] },
  { emoji: '🎀', name: 'ribbon', keywords: ['gift'] },
  { emoji: '🎈', name: 'balloon', keywords: ['party'] },
  { emoji: '🎉', name: 'party popper', keywords: ['party', 'celebrate'] },
  { emoji: '🎊', name: 'confetti ball', keywords: ['party'] },
  { emoji: '🎋', name: 'tanabata tree', keywords: ['japanese'] },
  { emoji: '🎍', name: 'pine decoration', keywords: ['japanese'] },
  { emoji: '🎎', name: 'Japanese dolls', keywords: ['japanese'] },
  { emoji: '🎏', name: 'carp streamer', keywords: ['japanese'] },
  { emoji: '🎐', name: 'wind chime', keywords: ['japanese'] },
  { emoji: '🧧', name: 'red envelope', keywords: ['chinese', 'gift'] },
  { emoji: '🎑', name: 'moon viewing ceremony', keywords: ['japanese'] },
  { emoji: '🪩', name: 'mirror ball', keywords: ['disco'] },
  { emoji: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'] },
  { emoji: '🎄', name: 'Christmas tree', keywords: ['christmas'] },
  { emoji: '🎆', name: 'fireworks', keywords: ['celebration'] },
  { emoji: '🎇', name: 'sparkler', keywords: ['fireworks'] },
  { emoji: '🧨', name: 'firecracker', keywords: ['celebration'] },
];

const symbols: EmojiItem[] = [
  { emoji: '❤️', name: 'red heart', keywords: ['love'] },
  { emoji: '🧡', name: 'orange heart', keywords: ['love'] },
  { emoji: '💛', name: 'yellow heart', keywords: ['love'] },
  { emoji: '💚', name: 'green heart', keywords: ['love'] },
  { emoji: '💙', name: 'blue heart', keywords: ['love'] },
  { emoji: '💜', name: 'purple heart', keywords: ['love'] },
  { emoji: '🖤', name: 'black heart', keywords: ['love'] },
  { emoji: '🤍', name: 'white heart', keywords: ['love'] },
  { emoji: '🤎', name: 'brown heart', keywords: ['love'] },
  { emoji: '💔', name: 'broken heart', keywords: ['sad'] },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['love'] },
  { emoji: '💕', name: 'two hearts', keywords: ['love'] },
  { emoji: '💞', name: 'revolving hearts', keywords: ['love'] },
  { emoji: '💓', name: 'beating heart', keywords: ['love'] },
  { emoji: '💗', name: 'growing heart', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love'] },
  { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'] },
  { emoji: '💝', name: 'heart with ribbon', keywords: ['love'] },
  { emoji: '☮️', name: 'peace symbol', keywords: ['peace'] },
  { emoji: '✝️', name: 'latin cross', keywords: ['christian'] },
  { emoji: '☪️', name: 'star and crescent', keywords: ['islam'] },
  { emoji: '🕉️', name: 'om', keywords: ['hindu'] },
  { emoji: '☯️', name: 'yin yang', keywords: ['balance'] },
  { emoji: '✡️', name: 'star of David', keywords: ['jewish'] },
  { emoji: '🔯', name: 'dotted six-pointed star', keywords: ['star'] },
  { emoji: '♈', name: 'Aries', keywords: ['zodiac'] },
  { emoji: '♉', name: 'Taurus', keywords: ['zodiac'] },
  { emoji: '♊', name: 'Gemini', keywords: ['zodiac'] },
  { emoji: '♋', name: 'Cancer', keywords: ['zodiac'] },
  { emoji: '♌', name: 'Leo', keywords: ['zodiac'] },
  { emoji: '♍', name: 'Virgo', keywords: ['zodiac'] },
  { emoji: '♎', name: 'Libra', keywords: ['zodiac'] },
  { emoji: '♏', name: 'Scorpio', keywords: ['zodiac'] },
  { emoji: '♐', name: 'Sagittarius', keywords: ['zodiac'] },
  { emoji: '♑', name: 'Capricorn', keywords: ['zodiac'] },
  { emoji: '♒', name: 'Aquarius', keywords: ['zodiac'] },
  { emoji: '♓', name: 'Pisces', keywords: ['zodiac'] },
  { emoji: '⛎', name: 'Ophiuchus', keywords: ['zodiac'] },
  { emoji: '🔀', name: 'shuffle tracks button', keywords: ['random'] },
  { emoji: '🔁', name: 'repeat button', keywords: ['loop'] },
  { emoji: '🔂', name: 'repeat single button', keywords: ['loop'] },
  { emoji: '▶️', name: 'play button', keywords: ['play'] },
  { emoji: '⏩', name: 'fast-forward button', keywords: ['forward'] },
  { emoji: '⏭️', name: 'next track button', keywords: ['skip'] },
  { emoji: '⏯️', name: 'play or pause button', keywords: ['play'] },
  { emoji: '◀️', name: 'reverse button', keywords: ['back'] },
  { emoji: '⏪', name: 'fast reverse button', keywords: ['rewind'] },
  { emoji: '⏮️', name: 'last track button', keywords: ['previous'] },
  { emoji: '🔼', name: 'upwards button', keywords: ['up'] },
  { emoji: '⏫', name: 'fast up button', keywords: ['up'] },
  { emoji: '🔽', name: 'downwards button', keywords: ['down'] },
  { emoji: '⏬', name: 'fast down button', keywords: ['down'] },
  { emoji: '⏸️', name: 'pause button', keywords: ['pause'] },
  { emoji: '⏹️', name: 'stop button', keywords: ['stop'] },
  { emoji: '⏺️', name: 'record button', keywords: ['record'] },
  { emoji: '🔘', name: 'radio button', keywords: ['radio'] },
  { emoji: '🔳', name: 'white square button', keywords: ['button'] },
  { emoji: '🔲', name: 'black square button', keywords: ['button'] },
  { emoji: '⬛', name: 'black large square', keywords: ['square'] },
  { emoji: '⬜', name: 'white large square', keywords: ['square'] },
  { emoji: '◼️', name: 'black medium square', keywords: ['square'] },
  { emoji: '◻️', name: 'white medium square', keywords: ['square'] },
  { emoji: '◾', name: 'black medium-small square', keywords: ['square'] },
  { emoji: '◽', name: 'white medium-small square', keywords: ['square'] },
  { emoji: '🔶', name: 'large orange diamond', keywords: ['diamond'] },
  { emoji: '🔷', name: 'large blue diamond', keywords: ['diamond'] },
  { emoji: '🔸', name: 'small orange diamond', keywords: ['diamond'] },
  { emoji: '🔹', name: 'small blue diamond', keywords: ['diamond'] },
  { emoji: '🔺', name: 'red triangle pointed up', keywords: ['triangle'] },
  { emoji: '🔻', name: 'red triangle pointed down', keywords: ['triangle'] },
  { emoji: '💠', name: 'diamond with a dot', keywords: ['diamond'] },
  { emoji: '🔘', name: 'radio button', keywords: ['button'] },
  { emoji: '🔴', name: 'red circle', keywords: ['circle'] },
  { emoji: '🟠', name: 'orange circle', keywords: ['circle'] },
  { emoji: '🟡', name: 'yellow circle', keywords: ['circle'] },
  { emoji: '🟢', name: 'green circle', keywords: ['circle'] },
  { emoji: '🔵', name: 'blue circle', keywords: ['circle'] },
  { emoji: '🟣', name: 'purple circle', keywords: ['circle'] },
  { emoji: '🟤', name: 'brown circle', keywords: ['circle'] },
  { emoji: '⚫', name: 'black circle', keywords: ['circle'] },
  { emoji: '⚪', name: 'white circle', keywords: ['circle'] },
  { emoji: '🟥', name: 'red square', keywords: ['square'] },
  { emoji: '🟧', name: 'orange square', keywords: ['square'] },
  { emoji: '🟨', name: 'yellow square', keywords: ['square'] },
  { emoji: '🟩', name: 'green square', keywords: ['square'] },
  { emoji: '🟦', name: 'blue square', keywords: ['square'] },
  { emoji: '🟪', name: 'purple square', keywords: ['square'] },
  { emoji: '🟫', name: 'brown square', keywords: ['square'] },
  { emoji: '✅', name: 'check mark button', keywords: ['yes', 'done'] },
  { emoji: '☑️', name: 'check box with check', keywords: ['check'] },
  { emoji: '✔️', name: 'check mark', keywords: ['yes'] },
  { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong'] },
  { emoji: '❎', name: 'cross mark button', keywords: ['no'] },
  { emoji: '➕', name: 'plus', keywords: ['add'] },
  { emoji: '➖', name: 'minus', keywords: ['subtract'] },
  { emoji: '➗', name: 'divide', keywords: ['math'] },
  { emoji: '✖️', name: 'multiply', keywords: ['math'] },
  { emoji: '♾️', name: 'infinity', keywords: ['forever'] },
  { emoji: '‼️', name: 'double exclamation mark', keywords: ['exclamation'] },
  { emoji: '⁉️', name: 'exclamation question mark', keywords: ['surprise'] },
  { emoji: '❓', name: 'red question mark', keywords: ['question'] },
  { emoji: '❔', name: 'white question mark', keywords: ['question'] },
  { emoji: '❕', name: 'white exclamation mark', keywords: ['exclamation'] },
  { emoji: '❗', name: 'red exclamation mark', keywords: ['exclamation', 'warning'] },
  { emoji: '〰️', name: 'wavy dash', keywords: ['dash'] },
  { emoji: '💱', name: 'currency exchange', keywords: ['money'] },
  { emoji: '💲', name: 'heavy dollar sign', keywords: ['money'] },
  { emoji: '⚕️', name: 'medical symbol', keywords: ['medical'] },
  { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle'] },
  { emoji: '⚜️', name: 'fleur-de-lis', keywords: ['french'] },
  { emoji: '🔱', name: 'trident emblem', keywords: ['trident'] },
  { emoji: '📛', name: 'name badge', keywords: ['badge'] },
  { emoji: '🔰', name: 'Japanese symbol for beginner', keywords: ['beginner'] },
  { emoji: '⭕', name: 'hollow red circle', keywords: ['circle'] },
  { emoji: '✳️', name: 'eight-spoked asterisk', keywords: ['star'] },
  { emoji: '❇️', name: 'sparkle', keywords: ['sparkle'] },
  { emoji: '©️', name: 'copyright', keywords: ['copyright'] },
  { emoji: '®️', name: 'registered', keywords: ['registered'] },
  { emoji: '™️', name: 'trade mark', keywords: ['trademark'] },
  { emoji: '#️⃣', name: 'keycap: #', keywords: ['hash'] },
  { emoji: '*️⃣', name: 'keycap: *', keywords: ['star'] },
  { emoji: '0️⃣', name: 'keycap: 0', keywords: ['zero'] },
  { emoji: '1️⃣', name: 'keycap: 1', keywords: ['one'] },
  { emoji: '2️⃣', name: 'keycap: 2', keywords: ['two'] },
  { emoji: '3️⃣', name: 'keycap: 3', keywords: ['three'] },
  { emoji: '4️⃣', name: 'keycap: 4', keywords: ['four'] },
  { emoji: '5️⃣', name: 'keycap: 5', keywords: ['five'] },
  { emoji: '6️⃣', name: 'keycap: 6', keywords: ['six'] },
  { emoji: '7️⃣', name: 'keycap: 7', keywords: ['seven'] },
  { emoji: '8️⃣', name: 'keycap: 8', keywords: ['eight'] },
  { emoji: '9️⃣', name: 'keycap: 9', keywords: ['nine'] },
  { emoji: '🔟', name: 'keycap: 10', keywords: ['ten'] },
  { emoji: '🔠', name: 'input latin uppercase', keywords: ['abc'] },
  { emoji: '🔡', name: 'input latin lowercase', keywords: ['abc'] },
  { emoji: '🔢', name: 'input numbers', keywords: ['123'] },
  { emoji: '🔣', name: 'input symbols', keywords: ['symbols'] },
  { emoji: '🔤', name: 'input latin letters', keywords: ['abc'] },
  { emoji: '🅰️', name: 'A button', keywords: ['blood'] },
  { emoji: '🆎', name: 'AB button', keywords: ['blood'] },
  { emoji: '🅱️', name: 'B button', keywords: ['blood'] },
  { emoji: '🆑', name: 'CL button', keywords: ['clear'] },
  { emoji: '🆒', name: 'COOL button', keywords: ['cool'] },
  { emoji: '🆓', name: 'FREE button', keywords: ['free'] },
  { emoji: 'ℹ️', name: 'information', keywords: ['info'] },
  { emoji: '🆔', name: 'ID button', keywords: ['identity'] },
  { emoji: 'Ⓜ️', name: 'circled M', keywords: ['metro'] },
  { emoji: '🆕', name: 'NEW button', keywords: ['new'] },
  { emoji: '🆖', name: 'NG button', keywords: ['no good'] },
  { emoji: '🅾️', name: 'O button', keywords: ['blood'] },
  { emoji: '🆗', name: 'OK button', keywords: ['ok'] },
  { emoji: '🅿️', name: 'P button', keywords: ['parking'] },
  { emoji: '🆘', name: 'SOS button', keywords: ['help', 'emergency'] },
  { emoji: '🆙', name: 'UP! button', keywords: ['up'] },
  { emoji: '🆚', name: 'VS button', keywords: ['versus'] },
  { emoji: '🈁', name: 'Japanese "here" button', keywords: ['japanese'] },
  { emoji: '🈶', name: 'Japanese "not free of charge" button', keywords: ['japanese'] },
  { emoji: '🈯', name: 'Japanese "reserved" button', keywords: ['japanese'] },
  { emoji: '🉐', name: 'Japanese "bargain" button', keywords: ['japanese'] },
  { emoji: '🈹', name: 'Japanese "discount" button', keywords: ['japanese'] },
  { emoji: '🈚', name: 'Japanese "free of charge" button', keywords: ['japanese'] },
  { emoji: '🈲', name: 'Japanese "prohibited" button', keywords: ['japanese'] },
  { emoji: '🉑', name: 'Japanese "acceptable" button', keywords: ['japanese'] },
  { emoji: '🈸', name: 'Japanese "application" button', keywords: ['japanese'] },
  { emoji: '🈴', name: 'Japanese "passing grade" button', keywords: ['japanese'] },
  { emoji: '🈳', name: 'Japanese "vacancy" button', keywords: ['japanese'] },
  { emoji: '㊗️', name: 'Japanese "congratulations" button', keywords: ['japanese'] },
  { emoji: '㊙️', name: 'Japanese "secret" button', keywords: ['japanese'] },
  { emoji: '🈺', name: 'Japanese "open for business" button', keywords: ['japanese'] },
  { emoji: '🈵', name: 'Japanese "no vacancy" button', keywords: ['japanese'] },
  { emoji: '🔴', name: 'red circle', keywords: ['circle'] },
  { emoji: '🟠', name: 'orange circle', keywords: ['circle'] },
  { emoji: '🟡', name: 'yellow circle', keywords: ['circle'] },
  { emoji: '🟢', name: 'green circle', keywords: ['circle'] },
  { emoji: '🔵', name: 'blue circle', keywords: ['circle'] },
  { emoji: '🟣', name: 'purple circle', keywords: ['circle'] },
  { emoji: '⚫', name: 'black circle', keywords: ['circle'] },
  { emoji: '⚪', name: 'white circle', keywords: ['circle'] },
];

const flags: EmojiItem[] = [
  { emoji: '🏳️', name: 'white flag', keywords: ['surrender'] },
  { emoji: '🏴', name: 'black flag', keywords: ['flag'] },
  { emoji: '🏁', name: 'chequered flag', keywords: ['race', 'finish'] },
  { emoji: '🚩', name: 'triangular flag', keywords: ['red flag'] },
  { emoji: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'lgbtq'] },
  { emoji: '🏳️‍⚧️', name: 'transgender flag', keywords: ['trans', 'lgbtq'] },
  { emoji: '🏴‍☠️', name: 'pirate flag', keywords: ['pirate'] },
  { emoji: '🇺🇸', name: 'flag: United States', keywords: ['usa', 'america'] },
  { emoji: '🇬🇧', name: 'flag: United Kingdom', keywords: ['uk', 'britain'] },
  { emoji: '🇨🇦', name: 'flag: Canada', keywords: ['canada'] },
  { emoji: '🇦🇺', name: 'flag: Australia', keywords: ['australia'] },
  { emoji: '🇫🇷', name: 'flag: France', keywords: ['france'] },
  { emoji: '🇩🇪', name: 'flag: Germany', keywords: ['germany'] },
  { emoji: '🇮🇹', name: 'flag: Italy', keywords: ['italy'] },
  { emoji: '🇪🇸', name: 'flag: Spain', keywords: ['spain'] },
  { emoji: '🇯🇵', name: 'flag: Japan', keywords: ['japan'] },
  { emoji: '🇰🇷', name: 'flag: South Korea', keywords: ['korea'] },
  { emoji: '🇨🇳', name: 'flag: China', keywords: ['china'] },
  { emoji: '🇮🇳', name: 'flag: India', keywords: ['india'] },
  { emoji: '🇧🇷', name: 'flag: Brazil', keywords: ['brazil'] },
  { emoji: '🇲🇽', name: 'flag: Mexico', keywords: ['mexico'] },
  { emoji: '🇷🇺', name: 'flag: Russia', keywords: ['russia'] },
  { emoji: '🇳🇱', name: 'flag: Netherlands', keywords: ['netherlands', 'dutch'] },
  { emoji: '🇸🇪', name: 'flag: Sweden', keywords: ['sweden'] },
  { emoji: '🇳🇴', name: 'flag: Norway', keywords: ['norway'] },
  { emoji: '🇩🇰', name: 'flag: Denmark', keywords: ['denmark'] },
  { emoji: '🇫🇮', name: 'flag: Finland', keywords: ['finland'] },
  { emoji: '🇵🇱', name: 'flag: Poland', keywords: ['poland'] },
  { emoji: '🇹🇷', name: 'flag: Turkey', keywords: ['turkey'] },
  { emoji: '🇸🇦', name: 'flag: Saudi Arabia', keywords: ['saudi'] },
  { emoji: '🇦🇪', name: 'flag: United Arab Emirates', keywords: ['uae'] },
  { emoji: '🇮🇱', name: 'flag: Israel', keywords: ['israel'] },
  { emoji: '🇪🇬', name: 'flag: Egypt', keywords: ['egypt'] },
  { emoji: '🇿🇦', name: 'flag: South Africa', keywords: ['south africa'] },
  { emoji: '🇳🇬', name: 'flag: Nigeria', keywords: ['nigeria'] },
  { emoji: '🇰🇪', name: 'flag: Kenya', keywords: ['kenya'] },
  { emoji: '🇦🇷', name: 'flag: Argentina', keywords: ['argentina'] },
  { emoji: '🇨🇴', name: 'flag: Colombia', keywords: ['colombia'] },
  { emoji: '🇨🇱', name: 'flag: Chile', keywords: ['chile'] },
  { emoji: '🇵🇪', name: 'flag: Peru', keywords: ['peru'] },
  { emoji: '🇹🇭', name: 'flag: Thailand', keywords: ['thailand'] },
  { emoji: '🇻🇳', name: 'flag: Vietnam', keywords: ['vietnam'] },
  { emoji: '🇮🇩', name: 'flag: Indonesia', keywords: ['indonesia'] },
  { emoji: '🇵🇭', name: 'flag: Philippines', keywords: ['philippines'] },
  { emoji: '🇲🇾', name: 'flag: Malaysia', keywords: ['malaysia'] },
  { emoji: '🇸🇬', name: 'flag: Singapore', keywords: ['singapore'] },
  { emoji: '🇳🇿', name: 'flag: New Zealand', keywords: ['new zealand'] },
  { emoji: '🇨🇭', name: 'flag: Switzerland', keywords: ['switzerland'] },
  { emoji: '🇦🇹', name: 'flag: Austria', keywords: ['austria'] },
  { emoji: '🇧🇪', name: 'flag: Belgium', keywords: ['belgium'] },
  { emoji: '🇮🇪', name: 'flag: Ireland', keywords: ['ireland'] },
  { emoji: '🇵🇹', name: 'flag: Portugal', keywords: ['portugal'] },
  { emoji: '🇬🇷', name: 'flag: Greece', keywords: ['greece'] },
  { emoji: '🇺🇦', name: 'flag: Ukraine', keywords: ['ukraine'] },
  { emoji: '🇷🇴', name: 'flag: Romania', keywords: ['romania'] },
  { emoji: '🇨🇿', name: 'flag: Czechia', keywords: ['czech'] },
  { emoji: '🇭🇺', name: 'flag: Hungary', keywords: ['hungary'] },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: 'frequent', name: 'Frequently Used', icon: '🕐', emojis: [] }, // populated dynamically
  { id: 'smileys', name: 'Smileys & People', icon: '😀', emojis: smileys },
  { id: 'animals', name: 'Animals & Nature', icon: '🐶', emojis: animals },
  { id: 'food', name: 'Food & Drink', icon: '🍔', emojis: food },
  { id: 'activities', name: 'Activities', icon: '⚽', emojis: activities },
  { id: 'travel', name: 'Travel & Places', icon: '✈️', emojis: travel },
  { id: 'objects', name: 'Objects', icon: '💡', emojis: objects },
  { id: 'symbols', name: 'Symbols', icon: '❤️', emojis: symbols },
  { id: 'flags', name: 'Flags', icon: '🏳️', emojis: flags },
];

// All emojis flattened for search
const ALL_EMOJIS: EmojiItem[] = EMOJI_CATEGORIES.slice(1).flatMap((c) => c.emojis);

export function searchEmojis(query: string): EmojiItem[] {
  if (!query) return [];
  const q = query.toLowerCase();
  const results: EmojiItem[] = [];
  for (const item of ALL_EMOJIS) {
    if (
      item.name.includes(q) ||
      item.keywords.some((kw) => kw.includes(q))
    ) {
      results.push(item);
      if (results.length >= 50) break;
    }
  }
  return results;
}

type FrequentEntry = { emoji: string; name: string; count: number };

function loadFrequent(): FrequentEntry[] {
  try {
    const raw = localStorage.getItem(FREQUENT_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as FrequentEntry[];
  } catch {
    return [];
  }
}

export function getFrequentEmojis(): EmojiItem[] {
  return loadFrequent()
    .sort((a, b) => b.count - a.count)
    .slice(0, MAX_FREQUENT)
    .map((e) => ({ emoji: e.emoji, name: e.name, keywords: [] }));
}

export function recordEmojiUsage(item: EmojiItem): void {
  const list = loadFrequent();
  const existing = list.find((e) => e.emoji === item.emoji);
  if (existing) {
    existing.count++;
  } else {
    list.push({ emoji: item.emoji, name: item.name, count: 1 });
  }
  // Keep only top entries
  list.sort((a, b) => b.count - a.count);
  localStorage.setItem(FREQUENT_KEY, JSON.stringify(list.slice(0, MAX_FREQUENT * 2)));
}
